language: java
jdk: oraclejdk7
script: mvn install -B
notifications:
  hipchat:
    rooms:
      secure: M5HkXCTdwtYHR/e1EQRAlpcYRyNd5zKjVudvIDfrpgA/W742s+gRepWLjYLEeF6mdsFc2oo7LDNIxim7e44TwxjMQHTZ4o0D3nWmukX3yRJGlHSJYP1YdMQPQK/JXAheQC8AlBxw69jQtglUrF3NaWtoRyeeWglP0sP5d4jNlLE=
