language: java
jdk: oraclejdk7
before_install:
# Maven 3.1.1
  - wget http://www.us.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
  - tar xvf apache-maven-3.1.1-bin.tar.gz > /dev/null
  - export MVN_HOME=`pwd`/apache-maven-3.1.1
  - export PATH=${MVN_HOME}/bin/:${PATH}
  - mvn --version
# Install base Android SDK
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1
  - export COMPONENTS=build-tools-19.0.1,android-19,sysimg-19,extra-android-support
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/master/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
  - source ~/.android-sdk-installer/env

# Create and start emulator

  - echo no | android create avd --force -n torch_test_avd -t android-19 --abi armeabi-v7a
  - mksdcard -l torch_sdcard 64M torch_sdcard.bin
  - emulator -avd torch_test_avd -sdcard torch_sdcard.bin -no-skin -no-audio -no-window &

before_script:
  - wait_for_emulator

script: mvn install -B -Dandroid.device=torch_test_avd